task 1
ZvarunVolodymyr/practise pull request #2
Opened 2021-09-10 12:39 UTC by ZvarunVolodymyr

2021-09-16 12:03 UTC, tetianastoyko requested changes

2021-09-16 12:03 UTC, tetianastoyko commented on main.py
> +    while(flag):
Програма має бути розділена на декілька логічних частин:
Валідація
Алгорим (одновна задача)

2021-09-16 14:39 UTC, ZvarunVolodymyr reviewed
Розділення вводу, валідації та основного алгоритму. Скорочення коду

2021-09-23 15:28 UTC, tetianastoyko approved these changes

2021-10-07 09:23 UTC, tetianastoyko approved these changes

2021-10-24 13:35 UTC, merged