2 task
ZvarunVolodymyr/practise pull request #3
Opened 2021-09-17 08:07 UTC by ZvarunVolodymyr

1 варіант

2021-09-17 08:19 UTC, ZvarunVolodymyr reviewed
оптимізація сортування

2021-09-22 20:50 UTC, ZvarunVolodymyr reviewed
додано підрахунок операцій порівняння, виправлення помилок

2021-09-23 15:32 UTC, tetianastoyko requested changes

2021-09-23 15:32 UTC, tetianastoyko commented on main.py
> +def generate_array(n: int):
В цей метод мали б передаватись межі і довжина, оскільки межі можуть бути введені як з клавіатури, так і зчитані з файла, наприклад

2021-09-23 15:32 UTC, tetianastoyko commented on main.py
> +def comp_1(a, b):
Логічна назва повинна бути

2021-09-23 15:32 UTC, tetianastoyko commented on main.py
> +def comp_2(a, b):
Логічна назва повинна бути

2021-09-23 15:32 UTC, tetianastoyko commented on main.py
> +        operation_counter[0] += 1
Що за ііндекси 0, 1?? 
Можна використати іншу структуру даних для цього,  що буде більш логічним

2021-09-23 17:51 UTC, ZvarunVolodymyr reviewed
Розділення валідації, можна легко додавати нові умови валідації. Зміна назв певних функцій. Створення класів для підрахунку операцій

2021-09-30 17:03 UTC, tetianastoyko requested changes

2021-09-30 17:03 UTC, tetianastoyko commented on main.py
> +    n = int(n)
А тут використати input_validation?

2021-09-30 17:03 UTC, tetianastoyko commented on main.py
> +    k = int(k)
А тут використати input_validation?

2021-09-30 17:10 UTC, ZvarunVolodymyr commented on main.py
> +    k = int(k)
в цих обох випадках його не потрібно, бо гарантується, що якщо n(k) != 'exit', то воно або '1' або '2'

2021-09-30 17:11 UTC, ZvarunVolodymyr commented on main.py
> +    k = int(k)
також, input_validation зчитує нове значення, чого в даному випадку не потрібно

2021-10-05 07:17 UTC, closed without merging